version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=drskavoj
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tjv_semestral
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    external: true